//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace CLR.clinfo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_Iclient_info", Namespace="http://tempuri.org/")]
    public partial class client_info : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public client_info() {
            this.Url = global::CLR.Properties.Settings.Default.CLR_clinfo_client_info;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetInfoCompletedEventHandler GetInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Iclient_info/GetInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Result GetInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string inn, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string account) {
            object[] results = this.Invoke("GetInfo", new object[] {
                        inn,
                        account});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void GetInfoAsync(string inn, string account) {
            this.GetInfoAsync(inn, account, null);
        }
        
        /// <remarks/>
        public void GetInfoAsync(string inn, string account, object userState) {
            if ((this.GetInfoOperationCompleted == null)) {
                this.GetInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInfoOperationCompleted);
            }
            this.InvokeAsync("GetInfo", new object[] {
                        inn,
                        account}, this.GetInfoOperationCompleted, userState);
        }
        
        private void OnGetInfoOperationCompleted(object arg) {
            if ((this.GetInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInfoCompleted(this, new GetInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/cl_info")]
    public partial class Result {
        
        private string appeal_dateField;
        
        private int credit_TypeField;
        
        private bool credit_TypeFieldSpecified;
        
        private string eCAField;
        
        private string eCA_NumberField;
        
        private string eDRPOUField;
        
        private string giveAllowDateField;
        
        private string identifycodeField;
        
        private string last_Payment_DateField;
        
        private decimal next_PaymentField;
        
        private bool next_PaymentFieldSpecified;
        
        private string next_Payment_DateField;
        
        private string payment_intervalField;
        
        private int requisites_CheckField;
        
        private bool requisites_CheckFieldSpecified;
        
        private string card_lastdiggitsField;
        
        private string corraccountnoField;
        
        private int credit_checkField;
        
        private bool credit_checkFieldSpecified;
        
        private int credit_check_kabField;
        
        private bool credit_check_kabFieldSpecified;
        
        private decimal currmonth_paymentsField;
        
        private bool currmonth_paymentsFieldSpecified;
        
        private int daysoverdueField;
        
        private bool daysoverdueFieldSpecified;
        
        private string deal_dateField;
        
        private int deal_stateField;
        
        private bool deal_stateFieldSpecified;
        
        private string dealnoField;
        
        private int error_codeField;
        
        private bool error_codeFieldSpecified;
        
        private System.DateTime first_usageField;
        
        private bool first_usageFieldSpecified;
        
        private string firstrepaydateField;
        
        private decimal fullrepaymentField;
        
        private bool fullrepaymentFieldSpecified;
        
        private int id_dealField;
        
        private bool id_dealFieldSpecified;
        
        private decimal last_paymentField;
        
        private bool last_paymentFieldSpecified;
        
        private System.DateTime on_dateField;
        
        private bool on_dateFieldSpecified;
        
        private string status_dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Appeal_date {
            get {
                return this.appeal_dateField;
            }
            set {
                this.appeal_dateField = value;
            }
        }
        
        /// <remarks/>
        public int Credit_Type {
            get {
                return this.credit_TypeField;
            }
            set {
                this.credit_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Credit_TypeSpecified {
            get {
                return this.credit_TypeFieldSpecified;
            }
            set {
                this.credit_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ECA {
            get {
                return this.eCAField;
            }
            set {
                this.eCAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ECA_Number {
            get {
                return this.eCA_NumberField;
            }
            set {
                this.eCA_NumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EDRPOU {
            get {
                return this.eDRPOUField;
            }
            set {
                this.eDRPOUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GiveAllowDate {
            get {
                return this.giveAllowDateField;
            }
            set {
                this.giveAllowDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Identifycode {
            get {
                return this.identifycodeField;
            }
            set {
                this.identifycodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Last_Payment_Date {
            get {
                return this.last_Payment_DateField;
            }
            set {
                this.last_Payment_DateField = value;
            }
        }
        
        /// <remarks/>
        public decimal Next_Payment {
            get {
                return this.next_PaymentField;
            }
            set {
                this.next_PaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Next_PaymentSpecified {
            get {
                return this.next_PaymentFieldSpecified;
            }
            set {
                this.next_PaymentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Next_Payment_Date {
            get {
                return this.next_Payment_DateField;
            }
            set {
                this.next_Payment_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Payment_interval {
            get {
                return this.payment_intervalField;
            }
            set {
                this.payment_intervalField = value;
            }
        }
        
        /// <remarks/>
        public int Requisites_Check {
            get {
                return this.requisites_CheckField;
            }
            set {
                this.requisites_CheckField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Requisites_CheckSpecified {
            get {
                return this.requisites_CheckFieldSpecified;
            }
            set {
                this.requisites_CheckFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string card_lastdiggits {
            get {
                return this.card_lastdiggitsField;
            }
            set {
                this.card_lastdiggitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string corraccountno {
            get {
                return this.corraccountnoField;
            }
            set {
                this.corraccountnoField = value;
            }
        }
        
        /// <remarks/>
        public int credit_check {
            get {
                return this.credit_checkField;
            }
            set {
                this.credit_checkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool credit_checkSpecified {
            get {
                return this.credit_checkFieldSpecified;
            }
            set {
                this.credit_checkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int credit_check_kab {
            get {
                return this.credit_check_kabField;
            }
            set {
                this.credit_check_kabField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool credit_check_kabSpecified {
            get {
                return this.credit_check_kabFieldSpecified;
            }
            set {
                this.credit_check_kabFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal currmonth_payments {
            get {
                return this.currmonth_paymentsField;
            }
            set {
                this.currmonth_paymentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currmonth_paymentsSpecified {
            get {
                return this.currmonth_paymentsFieldSpecified;
            }
            set {
                this.currmonth_paymentsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int daysoverdue {
            get {
                return this.daysoverdueField;
            }
            set {
                this.daysoverdueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool daysoverdueSpecified {
            get {
                return this.daysoverdueFieldSpecified;
            }
            set {
                this.daysoverdueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string deal_date {
            get {
                return this.deal_dateField;
            }
            set {
                this.deal_dateField = value;
            }
        }
        
        /// <remarks/>
        public int deal_state {
            get {
                return this.deal_stateField;
            }
            set {
                this.deal_stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deal_stateSpecified {
            get {
                return this.deal_stateFieldSpecified;
            }
            set {
                this.deal_stateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dealno {
            get {
                return this.dealnoField;
            }
            set {
                this.dealnoField = value;
            }
        }
        
        /// <remarks/>
        public int error_code {
            get {
                return this.error_codeField;
            }
            set {
                this.error_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool error_codeSpecified {
            get {
                return this.error_codeFieldSpecified;
            }
            set {
                this.error_codeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime first_usage {
            get {
                return this.first_usageField;
            }
            set {
                this.first_usageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool first_usageSpecified {
            get {
                return this.first_usageFieldSpecified;
            }
            set {
                this.first_usageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string firstrepaydate {
            get {
                return this.firstrepaydateField;
            }
            set {
                this.firstrepaydateField = value;
            }
        }
        
        /// <remarks/>
        public decimal fullrepayment {
            get {
                return this.fullrepaymentField;
            }
            set {
                this.fullrepaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fullrepaymentSpecified {
            get {
                return this.fullrepaymentFieldSpecified;
            }
            set {
                this.fullrepaymentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int id_deal {
            get {
                return this.id_dealField;
            }
            set {
                this.id_dealField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_dealSpecified {
            get {
                return this.id_dealFieldSpecified;
            }
            set {
                this.id_dealFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal last_payment {
            get {
                return this.last_paymentField;
            }
            set {
                this.last_paymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool last_paymentSpecified {
            get {
                return this.last_paymentFieldSpecified;
            }
            set {
                this.last_paymentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime on_date {
            get {
                return this.on_dateField;
            }
            set {
                this.on_dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool on_dateSpecified {
            get {
                return this.on_dateFieldSpecified;
            }
            set {
                this.on_dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string status_date {
            get {
                return this.status_dateField;
            }
            set {
                this.status_dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetInfoCompletedEventHandler(object sender, GetInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591